- resources/views/components/main-layout.blade.php
changed page language from swedish to english
> change page language to english

- composer.json
- composer.lock
Here is a tutorial for how to use lucides library in laravel.
https://github.com/mallardduck/blade-lucide-icons/blob/main/README.md
> install lucide icon library

- resources/css/app.css
- resources/views/components/main-layout.blade.php
- tailwind.config.js
Added font, and created base design according to Figma project
> create base layout for main

- app/Http/Controllers/ActorController.php
- app/Http/Controllers/AdminController.php
- app/Http/Controllers/AuthController.php
- app/Http/Controllers/AwardController.php
- app/Http/Controllers/DirectorController.php
- app/Http/Controllers/GenreController.php
- app/Http/Controllers/ListMovieUserController.php
- app/Http/Controllers/MovieActorController.php
- app/Http/Controllers/MovieController.php
- app/Http/Controllers/MovieDirectorController.php
- app/Http/Controllers/MovieGenreController.php
- app/Http/Controllers/RatingController.php
- app/Http/Controllers/ReviewController.php
- app/Http/Controllers/SearchController.php
- app/Http/Controllers/UserController.php
- app/Http/Controllers/WatchlistController.php
Controller structure added. 
Resources added to the controllers where CRUD is necessary.
> created structure for controllers

- resources/views/components/button.blade.php
closes #78 
I made a button able to display primary colors and secondary colors. Also props for making it full in width
> create button component

- resources/views/components/avatar.blade.php
Made a avatar component with the function `isset(imageUrl)` to see if there is a custom image used as users profile picture. If `null` would show a placeholder.
All images will be centered no matter the size of the original image.
> create avatar component

- app/Http/Controllers/MovieController.php
> added movie-controller

- resources/views/homepage.blade.php
new Views added with map structure and the the views from before is deleted
> Reconstructed-views

- resources/views/components/button.blade.php
- resources/views/components/header.blade.php
- resources/views/components/logo.blade.php
- resources/views/components/main-layout.blade.php
- resources/views/components/navbar.blade.php
Ok responsive, need navmenu for mobile
> create navbar, change logo to not fixed

- resources/views/components/footer.blade.php
- resources/views/components/logo.blade.php
footer is now designed, linking correct pages are left
> create footer component

- app/Http/Controllers/AdminController.php
> admin-controller

- app/Http/Controllers/ActorController.php
Implemented that actors only shows up in a specific movie. It's connected to the actor & movie Model. 
Max 3 actors will be added to the movies fetched from the Movie model.
> Actor-Controller-created

- app/Http/Controllers/Auth/AuthController.php
- app/Http/Controllers/Controller.php
- Added Controller after accedently deleted it.
- Authcontroller created with show login/registration forms.
- Create user with username/password/email 
- Handle Login, registration & Log out
> Authcontroller-created

- resources/views/components/forward-page.blade.php
- resources/views/components/previous-page.blade.php
Previous page component created. Image shows without and with hover. Linking pages function will be created later on.
> create previous page component

- app/Http/Controllers/Auth/EmailVerificationController.php
- app/Http/Controllers/Auth/PasswordController.php
I have implemented all the function for password this include: - Show the form for change the password (Forgot password)
- Check if current password is correct.
- Update Password
- Handle password reset link
- Send reset link email using Laravel’s built-in password reset functionality
I have also don the correct routingfix for emailVerificationController
> passwordController-added-emailController-fix

- app/Http/Controllers/Auth/AuthenticatedSessionController.php
- app/Http/Controllers/Auth/ConfirmablePasswordController.php
- app/Http/Controllers/Auth/EmailVerificationNotificationController.php
- app/Http/Controllers/Auth/EmailVerificationPromptController.php
- app/Http/Controllers/Auth/NewPasswordController.php
- app/Http/Controllers/Auth/PasswordResetLinkController.php
- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/Auth/VerifyEmailController.php
Added files that were deleted in app/http/controller/auth
> Auth-fix-to-herd

- app/Http/Controllers/ReviewController.php
- routes/web.php
created review controller and updated routes for it
> Review controller

- resources/views/components/base-card.blade.php
- resources/views/components/header.blade.php
- resources/views/components/movie.blade.php
Closes #100
Created a responsive movie cover with `min-w-24`. Added hover and made short spelling corrections in base-layout-file. Here is a video of what ive done
https://github.com/user-attachments/assets/1a3ded1d-4f4e-4ea2-af95-fcd8e9a6ce19
Awaiting #109 and #110 for further development
> create movie component

- app/Http/Controllers/Auth/PasswordController.php
I have reset the PasswordController so it matches the breeze starter pack
> Reseted-PasswordController

- routes/web.php
Fixed Routes in Web that were connected to either unknown controllers or not existed. 
- Fixed Home Page error in  HERD 
before 'Homepage' --> corrected 'homepage' (this is connected to the home.blade
> Fixed-Routes-and-errorcodes

- routes/web.php
Forgot in the previous merge that the blade file is called home.blade not homepage.blade= Fixed now
> Changed-correct-route

- app/Http/Controllers/GenreController.php
- routes/web.php
Created genre controller and updated routes
> genrecontroller

- app/Http/Controllers/ListMovieUserController.php
- routes/web.php
Corrected the routes to adminController and MovieCustomList
> Routes-to-admin&CustomList

- resources/views/components/flag-post-modal.blade.php
Created the flag-post modal, still awaiting issue #159 so the checkboxes can be implemented. Image of the mobile and desktop version so far:
> create flag-post modal

- resources/views/components/footer.blade.php
- resources/views/components/logo.blade.php
Made the footer responsive
https://github.com/user-attachments/assets/221edf64-76de-4a7e-afc5-495fd0e42e5b
> fix footer

- app/Http/Controllers/AwardController.php
- routes/web.php
created awardcontroller and updated routes
> awardcontroller

- app/Http/Controllers/RatingController.php
- routes/web.php
Created ratingController and included the controller in routes
> rating-controller

- app/Http/Controllers/WatchlistController.php
- routes/web.php
Created watchlistcontroller and updated routes
> watchlist-controller

- routes/web.php
I have added/change the file in blade to show: This is to show one specific movie ("id") 
Also corrected the route to match
> Routes movie

- resources/views/components/forward-page.blade.php
Created linking function to forward button, the URL will now change when clicking the button
> add linking pages to forward button

- resources/views/components/previous-page.blade.php
Created linking function to previous button, the URL will now change when clicking the button
> add linking pages to previous button

- resources/views/components/tag.blade.php
- resources/views/home.blade.php
Created tag component. Waiting for the star component before finishing rating
> tag-component

- resources/views/components/checkbox.blade.php
- resources/views/components/flag-post-modal.blade.php
- resources/views/components/header.blade.php
Added checkboxes to the flag post modal. Images show both desktop and mobile version:
> add checkbox to flag post modal

- app/Http/Controllers/Auth/AuthenticatedSessionController.php
- routes/web.php
- I have added/deleted view file to match with the routes.
- Re arranged in routes to function
- fixed previous issue in the authenticController 
- Tested the routes and its 90% connected
> Views structure

- resources/views/components/button.blade.php
- resources/views/components/flag-post-modal.blade.php
Added font-medium option on button component. Image shows font options side by side:
> add font option to button

- app/Http/Controllers/Auth/AuthenticatedSessionController.php
- app/Http/Requests/Auth/LoginRequest.php
- resources/views/users/create-account.blade.php
- resources/views/users/log-in.blade.php
Made a log in page with working error handling. It works.
https://github.com/user-attachments/assets/a454c8ee-7a78-4818-a699-64807bce64db
video is epic fyi
> Create log in

- resources/views/components/list-card.blade.php
- resources/views/components/list-cover.blade.php
- resources/views/components/movie-card.blade.php
Created movie cards. Still waiting for issue #102 so bookmark can be added to the movie card. Images show both desktop and mobile version:
> Movie card

- resources/views/components/admin-layout.blade.php
Closes #214 
* Create Admin base layout.
* Fixed a spelling error in main-layout
> create admin base layout

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/Auth/AuthenticatedSessionController.php
- resources/views/admin/index.blade.php
- resources/views/components/accordion.blade.php
- resources/views/components/admin-layout.blade.php
- resources/views/components/aside.blade.php
- resources/views/users/log-in.blade.php
- routes/web.php
Closes #107 
hello world! Today ive created this fantastic sidebar hidden in something called `aside`. This is really nice, and uses my worst fear. An accordion component, da Da DAA!
Anyways.. it was fun, lets not do it again :)
* It is not responsive (yet)
* Can log out
* Is in admin-layout
Added TODO in `routes/web.php` that i have commited changes for the admin middleware, since we dont have a nicer way to log in yet.
https://github.com/user-attachments/assets/7c37fd6b-4128-4c9b-83f5-a06ed3312f4d
> Create admin sidebar

- resources/views/components/rating.blade.php
- resources/views/components/tag.blade.php
I put rating component and tag component into different files since I accidentaly created them in the same file.
Edit: I also deleted a empty file named "ratings.blade.php" that was extra for some reason
> seperating of components

- resources/views/components/main-layout.blade.php
- resources/views/components/user-review.blade.php
Created a user review accordion.
https://github.com/user-attachments/assets/f1909d15-34a5-4403-871e-7042b4202a7a
> Review accordion

- database/factories/MovieListFactory.php
- database/seeders/DatabaseSeeder.php
- database/seeders/MovieListSeeder.php
- database/seeders/MovieSeeder.php
I have created seeders for lists and pivot table between movies and list. All tested using `php artisan db:seed`. It was a new experience :-)
> create list seeders

- resources/views/components/base-card.blade.php
- resources/views/components/list-card.blade.php
- resources/views/components/movie-card.blade.php
Fixed base-card components to optionally be a link or to be opened.
Also formated some files..
> Fix base card

- database/factories/MovieListFactory.php
- database/factories/ReviewFactory.php
- database/migrations/2025_02_04_163222_create_movies_table.php
- database/migrations/2025_02_04_163719_create_reviews_table.php
- database/migrations/2025_02_04_173903_create_lists_table.php
- database/seeders/DatabaseSeeder.php
- database/seeders/ReviewSeeder.php
* Created `ReviewFactory`
* Created `ReviewSeeder`
* Changed `string` to `text`  in movies table
* Add `title` to reviews table
* Add `description` to lists table
> add missing database fields and seeders

- resources/views/genres/show.blade.php
Created the specific genre page. Recording shows both desktop and mobile version.
https://github.com/user-attachments/assets/183371c0-4a3d-43e1-aaab-b9cac31ba0b4
> Render specific genre page

- resources/views/components/movie.blade.php
- resources/views/genres/index.blade.php
- resources/views/genres/show.blade.php
- resources/views/home.blade.php
made it so you can press a movie to enter `movies/show/:id` page
> make movies clickable on every instance

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/UserController.php
- resources/views/admin/admin-users-edit.blade.php
- resources/views/admin/admin-users-index.blade.php
- routes/web.php
In the video you can see the user's settings page for admin and how it is connected with the edit user page. You can also see the URL in the video if you want to test it yourself :)
What's been done:
When I tried to do the artistan route:list command I got an error that there is doubles of functions with the same name in userController. I then needed to delete the doubles before I could keep going. 
I also needed to change from "name" to "username" in adminController on line 63, to match the column name in the database. 
I added "username" on line 90 in web.php since that was needed to match what is send from the form.
I added the needed code in users-edit blade so that the connection with users-index would be made. with other words, so that the cancel and save button would work and …
> Render admin user's settings
